declare module '*.scss';
declare module "*.png";
declare module "*.svg";
declare module "*.jpeg";
declare module "*.jpg";
declare module "*.gif";
declare module "*.webp";
declare module "*.pdf";
declare module "*.apk";